require('dotenv').config();
const { Telegraf } = require('telegraf');
const { GoogleGenAI } = require('@google/genai');
const express = require('express');

// ==========================================
// 1. SETUP SERVER EXPRESS (UNTUK RAILWAY)
// ==========================================
const app = express();
const port = process.env.PORT || 3000;

app.get('/', (req, res) => {
  res.send('Server Bot Telegram AI sedang berjalan mantap!');
});

app.listen(port, () => {
  console.log(`Server web pendukung jalan di port ${port}`);
});

// ==========================================
// 2. SETUP BOT TELEGRAM & GOOGLE AI
// ==========================================
const bot = new Telegraf(process.env.TELEGRAM_BOT_TOKEN);
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

// ==========================================
// 3. LOGIKA BOT
// ==========================================
bot.start((ctx) => {
  ctx.reply('Halo! Aku bot AI kualitas tinggi. Ketik /gambar [deskripsi] untuk membuat ilustrasi Vertical (9:16) super detail.');
});

bot.command('gambar', async (ctx) => {
  const userPrompt = ctx.message.text.split(' ').slice(1).join(' ');

  if (!userPrompt) {
    return ctx.reply('Kasih deskripsinya dong! Contoh: /gambar prajurit futuristik di Jakarta');
  }

  // Pesan loading ke user
  const loadingMessage = await ctx.reply(`Siaap! Sedang memproses gambar "${userPrompt}" dengan kualitas tertinggi (9:16). Tunggu sebentar ya...`);

  // Prompt Enhancer: Suntikan kata kunci agar gambar tajam dan ukurannya vertical
  const qualityEnhancer = "Masterpiece, ultra-detailed, photorealistic, 4K resolution, sharp focus, 8k, cinematic lighting, dramatic shadows, intricate details, highly professional, vertical portrait, aspect ratio 9:16. Scene: ";
  const finalPrompt = qualityEnhancer + userPrompt;

  try {
    // Memanggil model Gemini 3.1 Flash Image (Nano Banana 2)
    const response = await ai.models.generateContent({
        model: 'gemini-3.1-flash-image',
        contents: finalPrompt,
    });

    // Mengambil data Base64 dari response AI
    const base64Data = response.candidates[0].content.parts[0].inlineData.data;
    const imageBuffer = Buffer.from(base64Data, 'base64');

    // Menghapus pesan loading
    await ctx.telegram.deleteMessage(ctx.chat.id, loadingMessage.message_id);

    // Mengirim gambar hasil generate ke Telegram
    await ctx.replyWithPhoto(
      { source: imageBuffer }, 
      { caption: `✅ Hasil (9:16) untuk: "${userPrompt}"\n\n_Generated by AI_`, parse_mode: 'Markdown' }
    );

  } catch (error) {
    console.error('Error dari API AI:', error);
    await ctx.telegram.deleteMessage(ctx.chat.id, loadingMessage.message_id);
    ctx.reply('Waduh, terjadi kesalahan saat menghubungi AI. Mungkin prompt kamu terlalu kompleks, melanggar filter keamanan, atau server sedang sibuk.');
  }
});

// Menjalankan Bot
bot.launch()
  .then(() => console.log('Bot Image Generator Super Jalan!'))
  .catch((err) => console.error('Gagal menjalankan bot:', err));

// Graceful stop
process.once('SIGINT', () => bot.stop('SIGINT'));
process.once('SIGTERM', () => bot.stop('SIGTERM'));
